import "./globals.css";
import { store } from "@/redux/store";
import { Provider } from "react-redux";
import { Inter } from "next/font/google";
import { GlobalProvider } from "@/provider/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter}`}>
        <Provider store={store}>
          <GlobalProvider>{children}</GlobalProvider>
        </Provider>
      </body>
    </html>
  );
}
